// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Novo_Dev.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Core.Model.Produto", b =>
                {
                    b.Property<string>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acompanhamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Preço")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Model.Franquia", b =>
                {
                    b.Property<string>("FranquiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("HorarioDeAbertura")
                        .HasColumnType("TEXT");

                    b.Property<string>("HorarioDeFechamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("FranquiaId");

                    b.ToTable("Franquias");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            Nome = "Admin",
                            Regra = "admin",
                            Senha = "QL0AFWMIX8NRZTKeof9cXsvbvu8="
                        },
                        new
                        {
                            UserId = "2",
                            Nome = "Daniel",
                            Regra = "user",
                            Senha = "QL0AFWMIX8NRZTKeof9cXsvbvu8="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
